language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - "jruby-19mode"
before_install:
  - sudo apt-add-repository -y ppa:brad-froehle/backports # for LLVM 3.2 on Precise
  - sudo apt-get update -qq
  - sudo apt-get install llvm-3.2-dev
env:
  global:
    - LD_LIBRARY_PATH="/usr/lib/llvm-3.2/lib:$LD_LIBRARY_PATH"
    - PATH="/usr/lib/llvm-3.2/bin:$PATH"
