language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - "jruby-19mode"
before_install:
  - sudo echo 'deb http://debian.whitequark.org/llvm/ sid/' > /etc/apt/sources.list.d/whitequark
  - sudo echo 'deb-src http://debian.whitequark.org/llvm/ sid/' >> /etc/apt/sources.list.d/whitequark
  - sudo apt-get update -qq
  - sudo apt-get install llvm-3.2
  - bundle install
  - (cd ext/ruby-llvm-support && rake)
env:
  global:
    - LD_LIBRARY_PATH="/usr/lib/llvm-3.2/lib:$LD_LIBRARY_PATH"
    - PATH="/usr/lib/llvm-3.2/bin:$PATH"
